---
- name: u'yum install selinux-python'
  yum: name=libselinux-python state=present

- name: u'add epel repo for CentOS 6'
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo owner=root group=root mode=0644
  when: ansible_distribution_major_version == "6"

- name: u'add epel repo for CentOS 6'
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6 owner=root group=root mode=0644
  when: ansible_distribution_major_version == "6"

- name: u'add epel repo for CentOS 7'
  yum: name=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm state=present
  when: ansible_distribution_major_version == "7"
